### ISSUE TITLE
Please help with this erorrs

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#1]
Hi, I try to run the demo, but it reports the errors:

```
ERROR: Unable to locate a modulefile for 'gcc/6.2.0'
ERROR: Unable to locate a modulefile for 'R'
```

Best

**Comment by kkdey** [comment]
Hi @bitcometz , the `module load ...` lines are for user on a cluster. If you are running the script in a local machine with both gcc snd R on the path, you can just comment out these lines.

**Comment by bitcometz** [comment]
Thanks for your reply !!!

I try your method and it works. But I met another problem in the demo:

```Rscript
out1 = ABC_intergenic_bedgraph_calc(scores,
                                    output_cell = paste0(bed_dir, "/", annot_name),
                                    output_bed = paste0("ABC.bed")
                                   )
```

Eorros:
```
Error in names(x) <- value: 'names' attribute [4] must be the same length as the vector [0]
Traceback:

1. ABC_intergenic_bedgraph_calc(scores, output_cell = paste0(bed_dir, 
 .     "/", annot_name), output_bed = paste0("ABC.bed"))
2. `colnames<-`(`*tmp*`, value = c("chr", "start", "end", "TargetGene"))
```

Could you help with this problem?

Thanks !!!

**Comment by bitcometz** [comment]
Is something wrong with the *.gz files in the URL: https://alkesgroup.broadinstitute.org/LDSCORE/Dey_Enhancer_MasterReg/processed_data/
```
2021-06-28T18:18:19.153Z        0.1 kB         ABCpaper_NasserFulcoEngreitz2020_Blood_AvgHiC.txt.gz

```

The sizes of *.gz file are very small. Could you help with this problem?

And I cannot find the above file in another URL:
```
https://alkesgroup.broadinstitute.org/LDSCORE/DeepLearning/Dey_DeepBoost_Imperio/data_extra/
```

Thanks !!!
