### ISSUE TITLE
how to get the SNP numbers？

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#10]
hello，
I found in your paper :
![image](https://user-images.githubusercontent.com/13601652/129692921-dfecc098-448a-4e71-bc5d-b87d9928ddc3.png)

and the number **5,961,159** was also used in your R:
https://github.com/kkdey/GSSG/blob/master/code/ldsc/ldsc_postprocess_enrichment.R

Could you tell me how this number was obtained ？

Best

**Comment by kkdey** [comment]
This number is the total number common SNPs (not low frequency) used to compute the heritability and is smaller than the overall size of the annotation of ~10 mil that contains both common and low freq variants.

**Comment by bitcometz** [comment]
Dear kkdey, thanks for your reply !!!
So is it the same for each time when I used different gene sets (got from expression compares).
Or should I look into the output log files and get the numbers ?

Thanks !!!

Best

**Comment by kkdey** [comment]
Yes it would be the same each time across gene sets and traits, as it pertains to computing the overall heritability.

**Comment by bitcometz** [comment]
Thanks ！！！
