### ISSUE TITLE
How to calculate the Escore and pEscore？

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#11]
hello，
In your supplementary files from your sc-linker paper, there are escores for the cell types:
![image](https://user-images.githubusercontent.com/13601652/129693985-d0839bb2-7286-410a-92bf-cb69d5d43556.png)

Could you tell me how these escores  were calculated ？
Is it obtained from this R:
https://github.com/kkdey/GSSG/blob/master/code/ldsc/ldsc_postprocess_enrichment.R

Best

**Comment by kkdey** [comment]
@bitcometz Yes you can get the enrichment values for the annotation (Gene score x S2G) using this code from the sc-linker heritability analysis output, and do the same for the respective (All genes x S2G), and take the difference. Thats the E-score. The E-score if < 0 is taken as 0, as then it means the gene score is not informative over all genes.
