### ISSUE TITLE
how to calculate gene scores for healty tissues ？

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#12]
helllo， there are no gene scores for healty tissue, which is shown in your supplementary tables:

<html  xmlns:o="urn:schemas-microsoft-com:office:office"  xmlns:x="urn:schemas-microsoft-com:office:excel"  xmlns="http://www.w3.org/TR/REC-html40">
<head>

</head>
<body>

celltypes | traits | Escore | pEscore
-- | -- | -- | --
Bcells (1.0%) (Healthy) | Inflammatory bowel disease | 5.919 | 1.82E-05
Bcells (0.4%) (Disease Progression) | Inflammatory bowel disease | 7.063 | 3.68E-05
Dendritic cells (1.1%) (Healthy) | Inflammatory bowel disease | 8.524 | 2.86E-07
Dendritic cells (0.3%) (Disease Progression) | Inflammatory bowel disease | 6.673 | 0.000162

</body>

</html>

I’m wondering whether the calculation method of healthy tissue is the same as that of diseased tissue, but the comparison is reversed by using the scanpy:
```
sc.tl.rank_genes_groups
```

Best

**Comment by kkdey** [comment]
The healthy gene program is from the `xavier_colon` tissue set of gene scores on the website. The calculation of the healthy and diseae progression are a little different, you can check the Methods section of our paper.

**Comment by bitcometz** [comment]
Thanks for your reply !!!

But there not `'xavier_colon' : (datapath + '/colon/healthydata.h5ad', 'subject')` in the following website:
```
https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/scdata/
```

Is it the subset from the `ucdata.h5ad` with the conditions as 'healthy'?



Best

**Comment by kkdey** [comment]
Yes xavier_colon healthy cell tyoe program is derivd from ucdata.h5ad file. So, you ned to restrict yourself to healthy samples in that h5ad file and then compute the DE

**Comment by kkdey** [comment]
@bitcometz All healthy cell type programs are in 
https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/gene_scores/cell_type_programs/
Alzheimers: alzheimers_brain
UC: xavier_colon
MS: msbrain
Lung fibrosis: krasnow_lung
Lung asthma: asthma_healthy
Lung covid: idoamit_healthy

**Comment by bitcometz** [comment]
Thanks ！！！
