### ISSUE TITLE
Scripts for identifying driving heritability genes?

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#13]
hello, thanks for your help and I  have reached this step of analysis：
![image](https://user-images.githubusercontent.com/13601652/130361181-faf53b32-ff33-4e59-8952-9898641aa0c5.png)

But I am not familiar with MAGMA.

Could you provide some scripts used in your paper ?

Thanks !!!

**Comment by kkdey** [comment]
@bitcometz You can find the MAGMA scripts and manual here: https://ctg.cncr.nl/software/magma. Their manual has detailed examples of how MAGMA can be run for each summary stat. I computed these sometime back and do not have the exact scripts with me at the moment.

**Comment by bitcometz** [comment]
Thanks !!!
