### ISSUE TITLE
question about Escore

### ISSUE THREAD

**Issue by fanying2015** [kkdey/GSSG#14]
@kkdey Thank you for sharing the code for the calculation of Escore on https://github.com/kkdey/GSSG/blob/master/code/ldsc/ldsc_postprocess_enrichment.R
![image](https://user-images.githubusercontent.com/13603229/130464227-e2bbd54d-3cfd-4f9e-b29d-e8b89c488061.png)

I have two questions:
1) Does "myenrstat"  corresponds to the enrichment of annotation Ec in formula 
![image](https://user-images.githubusercontent.com/13603229/130464081-8d81dc70-6141-4abf-8d0a-2bae674e5784.png)
I failed to reproduce the Ec with the 3 lines of formula as shown above. The order of myenrstat is on 1e-07, which is very different from the numbers shown in the paper. myenrstat_z or myenrstat_sd also didn't match exactly.

2) In both taustar and enrichment score postprocess calculation, I noticed you did meta analysis with ldsc outputs from all traits (eg. brain traits, autoimmune-traits) using meta.summaries. Do I need to do meta analysis to get the Escore as shown in the paper? https://www.biorxiv.org/content/10.1101/2021.03.19.436212v1.full.pdf  I thought Escore can be calculated even with one trait (and ALL) as input. Let me know if I missed or misunderstood something.

Thank you!

**Comment by bitcometz** [comment]
@kkdey , I also met this problem. Could you help with this problem ?

Thanks !!!

**Comment by bitcometz** [comment]
@fanying2015 , you can also have a look at the following R script:

https://github.com/kkdey/singlecellLDSC/blob/master/code/postprocess_ldsc.R

**Comment by fanying2015** [comment]
> @fanying2015 , you can also have a look at the following R script:
> 
> https://github.com/kkdey/singlecellLDSC/blob/master/code/postprocess_ldsc.R

@bitcometz Thank you for sending me the link.
If my understanding is right, the enrichment from ldsc output is used directly. Escore = (enrichment_CellType - enrichment_ALL). Tau_star does require additional calculation from Jacknife output. This is the best I can get the moment.

I'm kind of concerned because the tool usage is different from some descriptions on the ldsc wikipage https://github.com/bulik/ldsc/wiki/Partitioned-Heritability-from-Continuous-Annotations. Also I checked the results deposited for colon and UC, and I don't quite get why M cells are not enriched in Cell Type program. But I think I'll proceed with my best guess at the moment.

Thank you!

**Comment by kkdey** [comment]
@fanying2015 The enrichments and standard errors used are from the 5th and 6th columns of the results file, the myenrstat calculation is just done to get a better estimate of significance. The Ec formula will not match with myenrstat because of this correction. You do not need to do meta-analysis to replicate sc-linker results as we treat each trait separately. Thats mainly for the previous accompanying pre-print [here](https://www.biorxiv.org/content/10.1101/2020.09.02.279059v3). 
For M cells, we had very few M cells in healthy colon which is why the cell type program DE analysis was severely underpowered. Maybe that explains your question.

**Comment by fanying2015** [comment]
@kkdey Thank you for the response and clarification. I was confused about M cells because the enrichment value for IBD is larger than the corresponding value for ALL. I'll try the myenrstat to estimate the signficance.
