### ISSUE TITLE
How to understand the degree of enrichment ??

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#15]
hello, @kkdey 

When I read your article, there is one thing that I don’t understand very well. The article mentions the following:

### Linking B cells, T cells and monocytes to immune-related diseases
```
We identified the expected cell type enrichments, including enrichment of erythroid cells for red blood
cell count and of B cells and T cells for lymphocyte percentage (Figure 2C, Figure S2A).
```
 * Figure 2C
 
![image](https://user-images.githubusercontent.com/13601652/132462458-384f8b58-f1c8-4b6f-945f-9a685908a207.png)

 * Figure S2A
 
![image](https://user-images.githubusercontent.com/13601652/132462554-2b452e26-571f-4872-ae35-a181bc176306.png)

The enrichment of erythroid cells is clear. 
However, besides B cells and T cells, the dendritic cells , monocytes, and megakaryocytes are also enriced for lymphocyte percentage.

Could you give me some suggestions to help me understand these results better？

Thanks !!!

Best

**Comment by kkdey** [comment]
I mean that relatively the positive control pairs have higher E-score and/or more significant p-value. It is not unexpected that you see enrichment of non-adptive immune cells for lymphocyte %age h2, as there is usually a lot of signaling and co-operative functionality across these immune cells, and also tagging cis-genetic effects with B/T cells. 
Something we have seen and updated in the revised manuscript is to look at pairs for which E-score > 1.5 and p-value is FDR (< 0.05) significant. In such a case, you will see most of the pairs coming up would be positive control ones.

**Comment by bitcometz** [comment]
Thanks !!! got it
