### ISSUE TITLE
How to interpret the results of healthy vs disease？

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#16]
hello， @kkdey 

Suppose I performed scRNA-Seq on 10 healthy and 10 diseased samples, my purpose is to find the cell types related to the diseased  **traitD**. 
Firstly， I can detect :
 * (a) cell types gene programs based on healthy samples 
 * (b) disease progression gene programs by comparing disease samples vs healthy samples 

And then compute the h2 scores for (a) and (b) with **traitD** GWAS summaries respectively.

In this case, for each celltype, there are three conditions that may be related to the disease：
 * (1) low in (a) cell types gene programs but high in (b) disease progression gene programs
 * (2) high in (a) cell types gene programs but low in (b) disease progression gene programs
 * (3) both high h2 score in  (a) cell types gene programs and (b) disease progression gene programs

Should I just consider the first condition, just highlight in the S2 Table:
![image](https://user-images.githubusercontent.com/13601652/132469697-64a79f14-f583-4978-bc41-a014a3e3898a.png)

Thanks !!!

Best

**Comment by kkdey** [comment]
We  would consider all three cases as interesting - the cell type programs and disease progression programs usually provide very unique information. Usually, you would encounter more of (3) or (2) as if a particular cell type is implicated for disease, its cell type program would be expected to be associated. This is why we highlight (1) as that is more unexpected and biologically novel.

**Comment by bitcometz** [comment]
Thanks !!!
