### ISSUE TITLE
Colud you provide the *ldsc.results files?

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#17]
hello, @kkdey ,

We are reproducing the results of your article according to the process you provided, but we don’t know if the results we made are similar to yours, so colud you  please  also provide the following results:

`*ldsc.results`, which is generated by ldsc.

Thanks !!!

**Comment by kkdey** [comment]
@bitcometz We do not maintain the .results file as they take up a large amount of storage. Instead, we extract the relevant files into a post-processed format which we currently share under sclinker_results.

**Comment by bitcometz** [comment]
Thanks !!! I will check the files
