### ISSUE TITLE
Missing files for scLinks

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#2]
hello,
In the script `geneset_to_bed_sclinker.sh`:
there are two files missing: `../../processed_data/ABC.listbloodQC.txt` and `../../processed_data/Roadmap_map_EID_names.txt`

they required in the function `ABC_Road_bedgraph_calc`
```Rscript
    if(tissuename == "BLD"){
      tissuenames2 = as.character(read.table("../../processed_data/ABC.listbloodQC.txt", header=F)[,1])
    }
  roadmap_meta = read.delim("../../processed_data/Roadmap_map_EID_names.txt",
                            header=F)
```

Could you help with this problem ?
Thanks !!!

**Comment by kkdey** [comment]
@bitcometz My apologies. I have uploaded the files here: https://alkesgroup.broadinstitute.org/LDSCORE/Dey_Enhancer_MasterReg/processed_data/
Please let me know if there are any other issues. thanks

**Comment by bitcometz** [comment]
@kkdey , thanks !!!

**Comment by twoneu** [comment]
Hi @kkdey, thank you for developing this package! It seems that there may be one file missing from the processed_data folder at the link above:

File '../../processed_data/AllPredictions.AvgHiC.ABC0.015.minus150.withcolnames.ForABCPaper.txt.gz' does not exist or is non-readable.

**Comment by kkdey** [comment]
@twoneu Sorry the file got moved accidentally, you should be able to find it now, thanks for checking!
