### ISSUE TITLE
Genome build of processed data for snp-to-gene linking files

### ISSUE THREAD

**Issue by xxihe** [kkdey/GSSG#24]
Hi @kkdey ,

I am interested in applying the snp-to-gene links published in sc-linker paper to our studies. However, I did not find any information about with reference genome is used in those published data, such as the Roadmap+ABC linking strategy (I believe the published file is at https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/Dey_Enhancer_MasterReg/processed_data/RoadmapUABCannot_regions_to_genes.txt.gz). Could you help me confirm which genome build this file is on? 

I checked the sc-linker paper, however, it only specific that the single cell data is on hg38, but dose not mention about which reference genome it is on for the snp-to-gene linking files used in that paper. 

I also checked the other paper (Dey, K.K., Gazal, S., van de Geijn, B., Kim, S.S., Nasser, J., Engreitz, J.M. and Price, A.L., 2022. SNP-to-gene linking strategies reveal contributions of enhancer-related and candidate master-regulator genes to autoimmune disease. Cell Genomics, 2(7), p.100145.). However, I did not find any relative information either. I noticed that there are several linking strategies other than Roadmap and ABC in this paper as well. Could you also help me verify the reference genome used in those strategies files?

Thank you very much!!!

**Comment by kkdey** [comment]
@xxihe Hi, the build for this data currently is hg19. 
We are moving to hg38 and will soon update on that.

**Comment by xxihe** [comment]
Thank you!

**Comment by happyhamm** [comment]
@kkdey  - Looking forward to that hg38 build. When might the hg38 data be available? Thanks!

**Comment by kkdey** [comment]
We are working on a new enhancer-gene linking strategy and updating ABC, EpiMap - all in hg38. It should be available in 1-2 months.
