### ISSUE TITLE
Data not accessible

### ISSUE THREAD

**Issue by elsiass** [kkdey/GSSG#25]
hello, @kkdey
I was intrigued by sc-linker, and I'm running this analysis.
But I can't access the data site of step 2 part. I wonder if this is my computer's problem or you blocked access.
Because until a few weeks ago, I was able to check the data here!
I would be grateful if you could answer me.
With affection.

**Comment by kkdey** [comment]
@elsiass We are making some changes to our bucket set up to lower egress rates. We will be back up by the end of the week - there may be some modifications to access paths. Please bear with us, thanks for using sc-linker and sorry for this inconvenience.

**Comment by kkdey** [comment]
@elsiass The webpage is up now. Thanks for your patience.
