### ISSUE TITLE
Help with the input files

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#3]
hello,

I am trying to run the script `run_ldsc_reg.sh`, but I do not the formats of the following files:

```
sumstats_taskfile=/n/groups/price/kushal/LDSC/ldsc/TASKFILES/sumstats_reduced_blood.txt
annot_taskfile=/n/groups/price/kushal/Enhancer_MasterReg/data/temp.txt
```

Could you provide an eample for the above files ?

Best

**Comment by kkdey** [comment]
Hi @bitcometz, threse are just files that contain the summary statistics 

```
head -n 5 /n/groups/price/kushal/LDSC/ldsc/TASKFILES/sumstats_reduced_blood.txt
UKB_460K.blood_RBC_DISTRIB_WIDTH.sumstats
UKB_460K.blood_RED_COUNT.sumstats
UKB_460K.blood_WHITE_COUNT.sumstats
UKB_460K.blood_PLATELET_COUNT.sumstats
UKB_460K.blood_EOSINOPHIL_COUNT.sumstats
```

For the annot_taskfile, I just used it to pass names of annotation folderss, example from the Enhancer-driven paper: https://www.biorxiv.org/content/10.1101/2020.09.02.279059v3

```
head -n 3 $annot_taskfile

EDS_Binary_top10
eQTL_CTS_prob
Expecto_MVP
```

The annotation folder has the following strcuture 

```
-Annotation folder (gene score specific)
   -  S2G1 folder (may be 100kb) 
   -  S2G2 folder (may be ABC)
   -

Hope this is clear

**Comment by bitcometz** [comment]
thanks !!!
