### ISSUE TITLE
Which weights files to used?

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#4]
hello，

in your script：
```
weights_path=/n/groups/price/ldsc/reference_files/1000G_EUR_Phase3/weights
```
And I found three weights files:
```
1000G_Phase3_EAS_weights_hm3_no_MHC.tgz
1000G_Phase3_weights_hm3_no_MHC.tgz
weights_hm3_no_hla.tgz
```

I am wondering which one is ued in the paper : `Identifying disease-critical cell types and cellular processes across the human body by integration of single-cell profiles and human genetics`

Could you help with this problem?

Best

**Comment by kkdey** [comment]
Hi @bitcometz, the relevant file would be 1000G_Phase3_weights_hm3_no_MHC.tgz.
You can also use the third one, however don't use the first set of files as it is for 
EAS (East Asians)

**Comment by bitcometz** [comment]
Thanks for your reply !!!
