### ISSUE TITLE
where can I find the 'sclinker_results'?

### ISSUE THREAD

**Issue by bitcometz** [kkdey/GSSG#5]
Hello,

The results of your article are very useful for my research, which is mentioned the this ReadMe.txt:
https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/Jagadeesh_Dey_sclinker/README.txt

But I cannot find the 'sclinker_results'.

Could you please provide these results?

Thanks !!!

Best

**Comment by kkdey** [comment]
Hi @bitcometz,

Thanks for pointing it out. The sclinker_results is now uploaded.
Thanks
Kushal

**Comment by bitcometz** [comment]
Thanks !!!
