### ISSUE TITLE
which LDSC annotation should I use?

### ISSUE THREAD

**Issue by fanying2015** [kkdey/GSSG#7]
@kkdey Thank you for uploading the resources and codes online. It is extremely helpful.

I have a question about the LDSC annotations uploaded. Here is the link for an example:
https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/annotations/cell_type_programs/ICA_bonemarrow/B_Lymphocytes_L2/
<img width="769" alt="Screen Shot 2021-08-11 at 3 55 23 PM" src="https://user-images.githubusercontent.com/13603229/129094765-1ff2bd0e-e015-4436-aa07-44f29a3a888b.png">

For B_lymphocyte, there are multiple options, should I use "ABC_Road_GI_BLD"? What's the difference between "ABC_Road_GI_BLD" and "ABC_Road_I_BLD"?

Thank you!

**Comment by fanying2015** [comment]
Also, in the disease progression annotation file, what's the difference between L2 and L3. Below is the link for an example: https://alkesgroup.broadinstitute.org/LDSCORE/Jagadeesh_Dey_sclinker/annotations/disease_progression_programs/UC/

There's 'Disease_Mast_L2' and 'Disease_Mast_L3' in UC for instance. 

Thank you!

**Comment by kkdey** [comment]
Hi @fanying2015, please use the ABC_Road_GI_BLD annotation. "GI" stands for both genic and intergenic enhancers, and "I" stands for only intergenic enhancers. Also L2 and L3 are cell-types annotated at two different resolutions, with L3 being a finer annotation of L2. We have primarily considered the L2 programs as they had appreciable gene set size compared t L3, and were less correlated with one another and therefore, were more well powered for sc-linker. So, you can ignore the L3 programs

**Comment by fanying2015** [comment]
> Hi @fanying2015, please use the ABC_Road_GI_BLD annotation. "GI" stands for both genic and intergenic enhancers, and "I" stands for only intergenic enhancers. Also L2 and L3 are cell-types annotated at two different resolutions, with L3 being a finer annotation of L2. We have primarily considered the L2 programs as they had appreciable gene set size compared t L3, and were less correlated with one another and therefore, were more well powered for sc-linker. So, you can ignore the L3 programs

Thank you for the quick response! Can't wait to try it on some GWAS data!
